Repository pulibrary/bibdata, pull requests merged in 2018-06, with the labels that each got.

#402 Ensuring that the ARK is extracted for JSON-LD regardless of the neighboring link text subfield value
  app/models/electronic_location.rb
  app/models/jsonld_record.rb
  spec/controllers/bibliographic_controller_spec.rb
  spec/fixtures/10002695.mrx
  spec/models/electronic_location_spec.rb
Labels: review

#403 update to voyager_helpers 0.6.5
  Gemfile
  Gemfile.lock
Labels: in progress

#404 Add uniform_title to JSON-LD display.
  app/models/jsonld_record.rb
  public/context.json
  spec/models/jsonld_record_spec.rb
Labels: in progress

#407 Add additional metadata fields to JSON-LD.
  app/models/jsonld_record.rb
  public/context.json
  spec/models/jsonld_record_spec.rb
Labels: in progress

#408 Adds language_iana_s field to support the IANA Language Subtag Registry
  marc_to_solr/lib/traject_config.rb
  marc_to_solr/spec/lib/config_spec.rb
Labels: review

#409 Add bibliographic_citation.
  app/models/jsonld_record.rb
  public/context.json
  spec/models/jsonld_record_spec.rb
Labels: in progress

#406 Ensures that the location code is also exposed in the JSON-LD representation of bib. resources
  app/models/jsonld_record.rb
  spec/models/jsonld_record_spec.rb
Labels: pomegranate, review

#410 remove unused sinatra gem
  Gemfile
  Gemfile.lock
Labels: in progress

#412 update to rails 5.1.6
  Gemfile.lock
Labels: in progress

#413 reject invalid language codes from iana language field
  marc_to_solr/lib/traject_config.rb
  marc_to_solr/spec/fixtures/sample1.mrx
  marc_to_solr/spec/lib/config_spec.rb
Labels: in progress
